export const REQUEST_SHOW_PENDING = "REQUEST_SHOW_PENDING";
export const REQUEST_SHOW_SUCCESS = "REQUEST_SHOW_SUCCESS";
export const REQUEST_SHOW_FAILED = "REQUEST_SHOW_FAILED";
export const REQUEST_EPISODELIST_PENDING = "REQUEST_EPISODELIST_PENDING";
export const REQUEST_EPISODELIST_SUCCESS = "REQUEST_EPISODELIST_SUCCESS";
export const REQUEST_EPISODELIST_FAILED = "REQUEST_EPISODELIST_FAILED";

export const REQUEST_EPISODE_PENDING = "REQUEST_EPISODE_PENDING";
export const REQUEST_EPISODE_SUCCESS = "REQUEST_EPISODE_SUCCESS";
export const REQUEST_EPISODE_FAILED = "REQUEST_EPISODE_FAILED";
